# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProyectoMC2(object):
    def setupUi(self, ProyectoMC2):
        ProyectoMC2.setObjectName("ProyectoMC2")
        ProyectoMC2.setEnabled(True)
        ProyectoMC2.resize(941, 708)
        self.centralwidget = QtWidgets.QWidget(ProyectoMC2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 691))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(6, 12, 931, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("interface/img/fondo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Cadena = QtWidgets.QPushButton(self.frame)
        self.Cadena.setGeometry(QtCore.QRect(570, 370, 281, 161))
        self.Cadena.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    background-color: rgb(61, 75, 131);\n"
"    text-align: center;\n"
"    font-size: 30px;\n"
"    text-transform: uppercase;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ffd700;  /* Color dorado */\n"
"    color:black;\n"
"}")
        self.Cadena.setObjectName("Cadena")
        ProyectoMC2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProyectoMC2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName("menubar")
        ProyectoMC2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProyectoMC2)
        self.statusbar.setObjectName("statusbar")
        ProyectoMC2.setStatusBar(self.statusbar)

        self.retranslateUi(ProyectoMC2)
        QtCore.QMetaObject.connectSlotsByName(ProyectoMC2)

    def retranslateUi(self, ProyectoMC2):
        _translate = QtCore.QCoreApplication.translate
        ProyectoMC2.setWindowTitle(_translate("ProyectoMC2", "MainWindow"))
        self.Cadena.setText(_translate("ProyectoMC2", "Cadena"))
