# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtn_cadena.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cadena(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(727, 684)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-20, -20, 771, 721))
        self.frame.setStyleSheet("background-color:rgb(61, 129, 131);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnIniciar = QtWidgets.QPushButton(self.frame)
        self.btnIniciar.setGeometry(QtCore.QRect(60, 70, 101, 41))
        self.btnIniciar.setStyleSheet("background-color: gray;\n"
"\n"
"color: white;\n"
"font-size: 20px;\n"
"")
        self.btnIniciar.setObjectName("btnIniciar")
        self.txtcampo = QtWidgets.QTextEdit(self.frame)
        self.txtcampo.setGeometry(QtCore.QRect(180, 70, 561, 41))
        self.txtcampo.setStyleSheet("background-color:white;\n"
"font-size: 15 px;\n"
"")
        self.txtcampo.setObjectName("txtcampo")
        self.btnSiguiente = QtWidgets.QPushButton(self.frame)
        self.btnSiguiente.setGeometry(QtCore.QRect(140, 370, 101, 41))
        self.btnSiguiente.setStyleSheet("background-color: rgb(255, 181, 165);\n"
"\n"
"color: black;\n"
"font-size: 20px;\n"
"")
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.lblImagen = QtWidgets.QLabel(self.frame)
        self.lblImagen.setGeometry(QtCore.QRect(390, 130, 351, 561))
        self.lblImagen.setStyleSheet("border: 2px solid black;")
        self.lblImagen.setText("")
        self.lblImagen.setPixmap(QtGui.QPixmap("interface/img/logo.jpg"))
        self.lblImagen.setScaledContents(True)
        self.lblImagen.setObjectName("lblImagen")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(30, 240, 341, 121))
        self.textBrowser.setStyleSheet("background-color:white;\n"
"border: 2px solid gray;\n"
"font-size: 15px;")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIniciar.setText(_translate("Dialog", "Iniciar"))
        self.btnSiguiente.setText(_translate("Dialog", "Siguiente"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Porfavor ingrese una cadena en el espacio quer esta arriba.</span></p></body></html>"))



