# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtn_semaforo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_simulacion_semaforo(object):
    def setupUi(self, simulacion_semaforo):
        simulacion_semaforo.setObjectName("simulacion_semaforo")
        simulacion_semaforo.resize(1067, 690)
        self.frame = QtWidgets.QFrame(simulacion_semaforo)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1071, 701))
        self.frame.setStyleSheet("background-color:rgb(61, 129, 131);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        # Botón de pausa (nuevo)
        self.btnPausa = QtWidgets.QPushButton(self.frame)
        self.btnPausa.setGeometry(QtCore.QRect(20, 20, 100, 40))
        self.btnPausa.setStyleSheet("""
            QPushButton {
                background-color: #f0f0f0;
                border: 2px solid #333;
                border-radius: 5px;
                font-size: 14px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: #e0e0e0;
            }
        """)
        self.btnPausa.setObjectName("btnPausa")
        self.btnPausa.setText("Pausar")
        
        self.lblDiagrama = QtWidgets.QLabel(self.frame)
        self.lblDiagrama.setGeometry(QtCore.QRect(770, 0, 291, 681))
        self.lblDiagrama.setText("")
        self.lblDiagrama.setPixmap(QtGui.QPixmap("interface/img/red_petri.png"))
        self.lblDiagrama.setScaledContents(True)
        self.lblDiagrama.setObjectName("lblDiagrama")
        
        # Contenedor de texto más alto (original 201 -> 221)
        self.txtDescripcion = QtWidgets.QTextBrowser(self.frame)
        self.txtDescripcion.setGeometry(QtCore.QRect(50, 60, 591, 330))  # Aumentado 20px
        self.txtDescripcion.setStyleSheet("""
            background-color: white;
            color: black;
            font-size: 20px;
            border: 2px solid #333;
            border-radius: 5px;
            padding: 10px;
        """)
        self.txtDescripcion.setObjectName("txtDescripcion")
        
        self.lblIntercepcion = QtWidgets.QLabel(self.frame)
        self.lblIntercepcion.setGeometry(QtCore.QRect(100, 410, 391, 221))
        self.lblIntercepcion.setText("")
        self.lblIntercepcion.setPixmap(QtGui.QPixmap("interface/img/intercepcion.png"))
        self.lblIntercepcion.setScaledContents(True)
        self.lblIntercepcion.setObjectName("lblIntercepcion")
        
        self.semaforo_secundario = QtWidgets.QLabel(self.frame)
        self.semaforo_secundario.setGeometry(QtCore.QRect(370, 440, 61, 131))
        self.semaforo_secundario.setText("")
        self.semaforo_secundario.setPixmap(QtGui.QPixmap("interface/img/luzVerde.png"))
        self.semaforo_secundario.setScaledContents(True)
        self.semaforo_secundario.setObjectName("label")
        
        self.semaforo_principal = QtWidgets.QLabel(self.frame)
        self.semaforo_principal.setGeometry(QtCore.QRect(200, 560, 141, 41))
        self.semaforo_principal.setText("")
        # Cargar y voltear la imagen horizontalmente (acostado)
        original_pixmap = QtGui.QPixmap("interface/img/luzRoja.png")
        transformado = original_pixmap.transformed(QtGui.QTransform().rotate(270))  # 90 grados a la derecha
        self.semaforo_principal.setPixmap(transformado)
        self.semaforo_principal.setScaledContents(True)
        self.semaforo_principal.setObjectName("semaforo_principal")

        self.retranslateUi(simulacion_semaforo)
        QtCore.QMetaObject.connectSlotsByName(simulacion_semaforo)

    def retranslateUi(self, simulacion_semaforo):
        _translate = QtCore.QCoreApplication.translate
        simulacion_semaforo.setWindowTitle(_translate("simulacion_semaforo", "Dialog"))
        self.txtDescripcion.setHtml(_translate("simulacion_semaforo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Luz verde 1 y luz roja 2 tiene un token.</span></p></body></html>"))