# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProyectoMC2(object):
    def setupUi(self, ProyectoMC2):
        ProyectoMC2.setObjectName("ProyectoMC2")
        ProyectoMC2.setEnabled(True)
        ProyectoMC2.resize(941, 708)
        self.centralwidget = QtWidgets.QWidget(ProyectoMC2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 691))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_fondo = QtWidgets.QLabel(self.frame)
        self.lbl_fondo.setGeometry(QtCore.QRect(6, 12, 931, 651))
        self.lbl_fondo.setStyleSheet("")
        self.lbl_fondo.setText("")
        self.lbl_fondo.setPixmap(QtGui.QPixmap("interface/img/fondo.jpg"))
        self.lbl_fondo.setScaledContents(True)
        self.lbl_fondo.setObjectName("lbl_fondo")
        self.btn_cadena = QtWidgets.QPushButton(self.frame)
        self.btn_cadena.setGeometry(QtCore.QRect(470, 490, 311, 141))
        self.btn_cadena.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    background-color: rgb(61, 75, 131);\n"
"    text-align: center;\n"
"    font-size: 30px;\n"
"    text-transform: uppercase;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ffd700;  /* Color dorado */\n"
"    color:black;\n"
"}")
        self.btn_cadena.setObjectName("btn_cadena")
        self.btn_Semaforo = QtWidgets.QPushButton(self.frame)
        self.btn_Semaforo.setGeometry(QtCore.QRect(110, 490, 261, 141))
        self.btn_Semaforo.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    background-color: rgb(61, 75, 131);\n"
"    text-align: center;\n"
"    font-size: 20px;\n"
"    text-transform: uppercase;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ffd700;  /* Color dorado */\n"
"    color:black;\n"
"}")
        self.btn_Semaforo.setObjectName("btn_Semaforo")
        self.txt_Nombres = QtWidgets.QTextBrowser(self.frame)
        self.txt_Nombres.setGeometry(QtCore.QRect(200, 290, 521, 171))
        self.txt_Nombres.setStyleSheet("    background-color: rgba(0, 0, 0, 180);  /* negro con transparencia */\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    border: 2px solid #333;\n"
"    border-radius: 5px;\n"
"")
        self.txt_Nombres.setObjectName("txt_Nombres")
        self.txt_Informacion = QtWidgets.QTextBrowser(self.frame)
        self.txt_Informacion.setGeometry(QtCore.QRect(10, 10, 921, 211))
        self.txt_Informacion.setStyleSheet("    background-color: rgba(0, 0, 0, 0);  /* negro con transparencia */\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    border: 2px solid #333;\n"
"    border-radius: 5px;\n"
"")
        self.txt_Informacion.setObjectName("txt_Informacion")
        self.lbl_oscFondo = QtWidgets.QLabel(self.frame)
        self.lbl_oscFondo.setGeometry(QtCore.QRect(-20, -30, 961, 731))
        self.lbl_oscFondo.setStyleSheet("    background-color: rgba(0, 0, 0, 180);  /* negro con transparencia */")
        self.lbl_oscFondo.setText("")
        self.lbl_oscFondo.setObjectName("lbl_oscFondo")
        self.lbl_fondo.raise_()
        self.lbl_oscFondo.raise_()
        self.btn_cadena.raise_()
        self.btn_Semaforo.raise_()
        self.txt_Nombres.raise_()
        self.txt_Informacion.raise_()
        ProyectoMC2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProyectoMC2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName("menubar")
        ProyectoMC2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProyectoMC2)
        self.statusbar.setObjectName("statusbar")
        ProyectoMC2.setStatusBar(self.statusbar)

        self.retranslateUi(ProyectoMC2)
        QtCore.QMetaObject.connectSlotsByName(ProyectoMC2)

    def retranslateUi(self, ProyectoMC2):
        _translate = QtCore.QCoreApplication.translate
        ProyectoMC2.setWindowTitle(_translate("ProyectoMC2", "MainWindow"))
        self.btn_cadena.setText(_translate("ProyectoMC2", "Cadena"))
        self.btn_Semaforo.setText(_translate("ProyectoMC2", "Simulacion de Semaforo"))
        self.txt_Nombres.setHtml(_translate("ProyectoMC2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Por:<br /><br />*   Jorge Aniabl Martínez Letona     -  201317952 -<br />*   Marlon Oved Juárez Hicho          -  202240677 -<br />*   Iván Antonio Álvarez Godínez    -  202003032 -</span></p></body></html>"))
        self.txt_Informacion.setHtml(_translate("ProyectoMC2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Matematica para computación 2 - Seccion B -</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Ing. Alfredo González<br />Aux. Eduardo René Agustín Mendoza<br />                                     </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30px; font-weight:600;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">                                                                                   Proyecto:<br />                  Simulacion de un semaforo de intersección y evaluación de cadenas con redes petri</span></p></body></html>"))

